development:
  adapter: postgresql
  encoding: unicode
  database: fblist_development
  pool: 5
  username: fblist
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: fblist_test
  pool: 5
  username: fblist
  password: password1